apiVersion: v1
kind: DeploymentConfig
metadata:
  name: image-observer
spec:
  replicas: 1
  selector:
    run: image-observer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: image-observer
    spec:
      containers:
      - image: pweil/image-observer
        imagePullPolicy: Always
        name: image-observer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
