apiVersion: v1
kind: DeploymentConfig
metadata:
  name: logging-es-aa0v5dqh
  namespace: logging
  labels:
    app: logging-es-template
    component: es
    logging-infra: elasticsearch
    provider: openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    component: es
    deployment: logging-es-aa0v5dqh
    provider: openshift
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logging-es-template
        component: es
        deployment: logging-es-aa0v5dqh
        provider: openshift
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: elasticsearch
          secret:
            secretName: logging-elasticsearch
            defaultMode: 420
        - name: elasticsearch-config
          configMap:
            name: logging-elasticsearch
            defaultMode: 420
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: logging-es-aa0v5dqh
      containers:
        - name: elasticsearch-prom-exporter
          image: 'docker.io/pweil/elasticsearch_exporter:latest'
          command:
            - /bin/elasticsearch_exporter
          args:
            - '-es.uri=https://localhost:9200'
            - '-es.ca=/etc/elasticsearch/secret/admin-ca'
            - '-es.client-cert=/etc/elasticsearch/secret/admin-cert'
            - '-es.client-private-key=/etc/elasticsearch/secret/admin-key'
          ports:
            - name: scraper
              containerPort: 9108
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
          volumeMounts:
            - name: elasticsearch
              readOnly: true
              mountPath: /etc/elasticsearch/secret
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
        - name: elasticsearch
          image: '172.30.194.97:5000/logging/logging-elasticsearch:latest'
          ports:
            - name: restapi
              containerPort: 9200
              protocol: TCP
            - name: cluster
              containerPort: 9300
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_TRUST_CERT
              value: 'true'
            - name: SERVICE_DNS
              value: logging-es-cluster
            - name: CLUSTER_NAME
              value: logging-es
            - name: INSTANCE_RAM
              value: 7680M
            - name: NODE_QUORUM
              value: '2'
            - name: RECOVER_AFTER_NODES
              value: '1'
            - name: RECOVER_EXPECTED_NODES
              value: '2'
            - name: RECOVER_AFTER_TIME
              value: 5m
          resources:
            limits:
              memory: 7680Mi
            requests:
              memory: 512Mi
          volumeMounts:
            - name: elasticsearch
              readOnly: true
              mountPath: /etc/elasticsearch/secret
            - name: elasticsearch-config
              readOnly: true
              mountPath: /usr/share/java/elasticsearch/config
            - name: elasticsearch-storage
              mountPath: /elasticsearch/persistent
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: infra
      serviceAccountName: aggregated-logging-elasticsearch
      serviceAccount: aggregated-logging-elasticsearch
      securityContext:
        supplementalGroups:
          - 65534
